project:
  type: website
  output-dir: _site

website:
  title: "Conflict and Compassion"
  favicon: "plots/Formal_1_Resized.jpg"
  navbar:
    left:
      - text: About me
        file: aboutme.qmd
      - text: Home
        file: index.qmd


format:
  html:
    toc: true
    smooth-scroll: true
    embed-resources: true
    code-copy: true
    code-overflow: wrap
    mainfont: "Monospace"

execute:
  echo: true
  freeze: auto
bibliography: references.bib
nocite: '@*'
resources:
  - plots/**

