project:
  type: website
  output-dir: _site

website:
  title: "Conflict and Compassion"
  navbar:
    left:
      - text: Home
        file: index.qmd

format:
  html:
    toc: true
    smooth-scroll: true
    embed-resources: true
    code-copy: true
    code-overflow: wrap
    mainfont: "Monospace"
execute:
  echo: true
  freeze: auto
bibliography: references.bib
nocite: '@*'
resources:
  - plots/**

