project:
  type: website

website:
  title: "Conflict and Compassion"
  navbar:
    left:
      - text: Home
        file: index.qmd
  page-footer:
    center: "© 2025 Nandini Kodali"

format:
  html:
    theme: default
    css: styles.css  # Add custom styles if you want to externalize the banner style
    toc: true
    smooth-scroll: true
    code-copy: true
    code-overflow: wrap
    embed-resources: true
    mainfont: "Monospace"

bibliography: references.bib
nocite: '@*'
