---
title: Conflict and Compassion
author: Nandini Kodali
format:
  html:
    smooth-scroll: true
    code-copy: true
    code-overflow: wrap
    toc: true
execute:
  echo: true
  warning: false
  message: false
  freeze: auto
lightbox: auto
editor: visual
embed-resources: true
bibliography: references.bib
nocite: '@*'
---

# Introduction

In zones of crisis and conflict, humanitarian aid workers play a crucial role in delivering lifesaving resources, facilitating medical care, and rebuilding community systems. But over the past two decades, these frontline workers have increasingly become targets themselves. Attacks on aid personnel have escalated both in number and complexity, driven by diverse actors ranging from insurgent groups to state militaries.
This report explores global patterns of violence against aid workers using data from the Aid Worker Security Database (AWSD). Through descriptive analytics, interactive mapping, and actor-specific breakdowns, the project examines how, where, and why humanitarian personnel are under threat. Built as an interactive Quarto website, this work combines rigorous data exploration with accessible storytelling to inform both policy and practice.

# Data and Methadology

